### ISSUE TITLE
Passing data from feature to feature

### ISSUE THREAD

**Issue by jeandavidhouzz** [rockbruno/RouterService#2]
Taking your README example, suppose I'd like to instantiate the LoginViewController with some data from the Profile feature, say a message string. From your README and your sample app, the only way I see such data can be passed is via the Route (like when you pass the hexColor). But LoginViewController is instantiated from the LoginFeature build method where the fromRoute parameter won't be of type LoginRoute. Any suggestion? Thanks!!!!

**Comment by rockbruno** [comment]
Hey there! The Route parameter is a protocol, you can cast it to LoginRoute inside the build method and retrieve the data. This is because you can have multiple routes pointing to the same feature :)

**Comment by jeandavidhouzz** [comment]
Sorry I am still confused about this build method from the `LoginFeature`:
```
static func build(dependencies: LoginFeature.Dependencies, fromRoute route: Route?) -> UIViewController 
```
Can the route param be any route? or is it the LoginRoute? 
If this is the LoginRoute, then I understand how I can instantiate it with some message.

**Comment by rockbruno** [comment]
Yes, It can be any route that from a RouteHandler that calls this feature :)

**Comment by rockbruno** [comment]
There is now a more complete example project that may help with this.
