### ISSUE TITLE
Stop shipping the pods in the example project

### ISSUE THREAD

**Issue by rockbruno** [rockbruno/RouterService#9]
There's a lot of diff when we edit the example project. We can instead generate the project and have the CI attempt to build and run the pods.

**Comment by ffittschen** [comment]
Hi @rockbruno, by _generate the project_, do you mean to use a tool like [XcodeGen](https://github.com/yonaskolb/XcodeGen), or do you mean to create the project once and just hook it up in a way so that pods are being built by the CI?

**Comment by rockbruno** [comment]
Hey @ffittschen ! Yeah I mean something like XcodeGen, although in this case I think it's possible to do it with Swift Package Manager.

**Comment by ffittschen** [comment]
Cool, I'll create a PR tomorrow with XcodeGen, as I couldn't find a way to have application targets in a `Package.swift` – I saw the individual targets of the example, but no executable I could actually _run_ on iOS.
